// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {books} from '../models';
import {main} from '../models';

export function ExecCommand(arg1:string):Promise<void>;

export function GetBookmarks():Promise<Array<books.BookmarkInfo>>;

export function GetCommandList():Promise<Array<main.Command>>;

export function Greet(arg1:string):Promise<string>;

export function Hide():Promise<void>;

export function OpenBook(arg1:string):Promise<void>;
