// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExecCommand(arg1) {
  return window['go']['main']['App']['ExecCommand'](arg1);
}

export function GetBooks(arg1) {
  return window['go']['main']['App']['GetBooks'](arg1);
}

export function GetCommandList() {
  return window['go']['main']['App']['GetCommandList']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function Hide() {
  return window['go']['main']['App']['Hide']();
}

export function OpenBook(arg1) {
  return window['go']['main']['App']['OpenBook'](arg1);
}

export function RecreateLibrary() {
  return window['go']['main']['App']['RecreateLibrary']();
}

export function Shutdown(arg1) {
  return window['go']['main']['App']['Shutdown'](arg1);
}
