// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExecCommand(arg1) {
  return window['go']['main']['App']['ExecCommand'](arg1);
}

export function GetCommandList() {
  return window['go']['main']['App']['GetCommandList']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}
