// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {library} from '../models';
import {main} from '../models';
import {context} from '../models';

export function ExecCommand(arg1:string):Promise<void>;

export function GetBooks(arg1:string):Promise<Array<library.Book>>;

export function GetCommandList():Promise<Array<main.Command>>;

export function Greet(arg1:string):Promise<string>;

export function Hide():Promise<void>;

export function OpenBook(arg1:string):Promise<void>;

export function Shutdown(arg1:context.Context):Promise<void>;
